<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BMIN503_FinalProject_Kanakamedala</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="BMIN503_FinalProject_Kanakamedala_files/libs/clipboard/clipboard.min.js"></script>
<script src="BMIN503_FinalProject_Kanakamedala_files/libs/quarto-html/quarto.js"></script>
<script src="BMIN503_FinalProject_Kanakamedala_files/libs/quarto-html/popper.min.js"></script>
<script src="BMIN503_FinalProject_Kanakamedala_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BMIN503_FinalProject_Kanakamedala_files/libs/quarto-html/anchor.min.js"></script>
<link href="BMIN503_FinalProject_Kanakamedala_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BMIN503_FinalProject_Kanakamedala_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BMIN503_FinalProject_Kanakamedala_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BMIN503_FinalProject_Kanakamedala_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BMIN503_FinalProject_Kanakamedala_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BMIN503_FinalProject_Kanakamedala</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="load-required-libraries" class="level1">
<h1>Load required libraries</h1>
<p>library(tidyverse)<br>
library(readr)<br>
library(lubridate)<br>
library(janitor)<br>
library(scales)<br>
library(broom)</p>
<hr>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Pediatric headache is a common primary care complaint, yet only a subset of patients require neurology evaluation, and even fewer need expedited specialty care. To standardize evaluation and triage, a Headache SmartForm was deployed across a pediatric primary care network to capture structured “red flag” symptoms. This project evaluates whether a derived red-flag scoring system based on SmartForm inputs aligns with actual neurology referral behavior and appropriately distinguishes between primary-care management, standard referral, and expedited referral needs.</p>
<p>1,451 headache encounters that utilized the smartform were analyzed and a red-flag score was constructed in which recurrent or persistent early morning vomiting and unsteady gait with headache were weighted as severe (1000 points each), whereas all other red flags were weighted as minor (1 point each). Scores of 0 recommended primary care management, 1–2 recommended standard neurology referral, and scores ≥3 recommended expedited referral. I compared score-based recommendations with clinicians’ actual orders and fit logistic regression models to examine whether severe and minor red flags predicted referral and concordance. The score aligned well with clinician behavior for low-risk encounters but overestimated the need for expedited referrals. Providers rarely followed expedited recommendations, indicating a need to recalibrate weights and thresholds before using this score as clinical decision support.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Headache is among the most frequent reasons for pediatric primary care visits. Although most headaches in children are benign, a subset may signal serious neurologic or systemic disease. Clinicians must balance avoiding unnecessary neurology referrals which contribute to long wait times and specialty clinic congestion against the risk of under-referring patients with high-risk features.</p>
<p>To support more consistent evaluation and triage, a standardized Headache SmartForm was deployed across CHOP’s large pediatric primary care network. The SmartForm captures “red flag” symptoms in discrete fields, including recurrent or persistent early morning vomiting, unsteady gait with headache, and several additional neurologic or systemic warning signs. These structured data elements enable derivation of a reproducible red-flag severity score that could ultimately inform decision support for neurology referrals.</p>
<p>In this project, we use routinely collected SmartForm data from 1,451 headache encounters to:</p>
<ol type="1">
<li><p>Construct and justify a red-flag severity score that distinguishes severe red flags (recurrent/persistent early morning vomiting and unsteady gait with headache) from minor red flags (all remaining questions).</p></li>
<li><p>Map the score to three clinically meaningful recommendation categories:</p>
<ul>
<li><p>Score 0 → primary care management / no neurology referral</p></li>
<li><p>Score 1–2 → standard neurology referral</p></li>
<li><p>Score ≥3 → expedited neurology referral</p></li>
</ul></li>
<li><p>Compare score-based recommendations with actual provider behavior using descriptive statistics, cross-tabulations, and concordance metrics.</p></li>
<li><p>Model the relationship between red-flag variables and both referral decisions and concordance using logistic regression.</p></li>
<li><p>Visualize referral patterns and agreement between recommendations and clinical actions.</p></li>
</ol>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">1.1 Data Source</h3>
<p>I analyzed 1,451 pediatric headache encounters from a pediatric primary care network in which the Headache SmartForm was used. Each row corresponds to one encounter and includes:</p>
<ul>
<li><p>Encounter metadata: date (<code>encounter_date</code>), department (<code>department_name</code>)</p></li>
<li><p>SmartForm headache red-flag indicators (binary *_ind fields)</p></li>
<li><p>Neurology referral indicators: any neurologic referral, standard referral, expedited referral</p></li>
<li><p>Educational material and ED referral indicators</p></li>
</ul>
<p>The dataset contains only structured, de-identified variables extracted from the EHR.</p>
</section>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">1.2 Data Cleaning</h3>
<p>Data cleaning focused on making variables interpretable and analysis-ready. We:</p>
<ol type="1">
<li><p><strong>Standardized column names</strong> using <code>janitor::clean_names()</code> to simplify reference in code.</p></li>
<li><p><strong>Converted encounter dates</strong> with <code>mdy()</code> to allow temporal analyses if needed.</p></li>
<li><p><strong>Replaced missing values</strong> in *_ind indicator fields with 0, reflecting that unchecked SmartForm options correspond to symptom absence or action not taken.</p></li>
<li><p><strong>Created consolidated referral variables</strong> to reflect operationally meaningful outcomes: any neurology referral, standard referral, and expedited referral.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries ----</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data directly from a fixed path</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>ha_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/Users/kanakamedl/Desktop/HA Neuro Referrals (2).csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1451 Columns: 19
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): ENCOUNTER_KEY, ENCOUNTER_DATE, DEPARTMENT_NAME
dbl (16): HA_MIGRAINE_DX_IND, REFERRAL_NEURO_IND, EXPEDITED_IND, STANDARDREF...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean variable names</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ha <span class="ot">&lt;-</span> ha_raw <span class="sc">|&gt;</span> <span class="fu">clean_names</span>()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert and recode missing inidcator fields and create referral outcome variables</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>ha <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">encounter_date =</span> <span class="fu">mdy</span>(encounter_date),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">across</span>(<span class="fu">ends_with</span>(<span class="st">"_ind"</span>), <span class="sc">~</span><span class="fu">replace_na</span>(., <span class="dv">0</span>)),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">any_neuro_referral =</span> referral_neuro_ind <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">standard_referral =</span> standardreferral_ind <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">expedited_referral =</span> expedited_ind <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I treated missing values in indicator fields as 0 because these columns represent discrete SmartForm checkboxes or order indicators, where an unchecked field meaningfully represents “not present” or “not ordered.” Consolidating referral indicators into <code>any_neuro_referral</code>, <code>standard_referral</code>, and <code>expedited_referral</code> aligns my outcomes with the triage pathways of interest.</p>
</section>
<section id="creating-the-red-flag-severity-score" class="level3">
<h3 class="anchored" data-anchor-id="creating-the-red-flag-severity-score">1.3 Creating the Red-Flag Severity Score</h3>
<p>I categorized red flags into <strong>severe</strong> and <strong>minor</strong> based on their expected clinical implications:</p>
<ul>
<li><p><strong>Severe red flags (1000 points each):</strong></p>
<ul>
<li><p>Recurrent or persistent early morning vomiting (<code>persistent_vomiting_ind</code>)</p></li>
<li><p>Unsteady gait with the headache (<code>unsteady_gait_ind</code>)</p></li>
</ul></li>
</ul>
<p>These features are particularly concerning for increased intracranial pressure or focal neurologic pathology and may warrant urgent or expedited evaluation.</p>
<ul>
<li><p><strong>Minor red flags (1 point each):</strong> All other documented red flags, such as:</p>
<ul>
<li><p>Persistent or continuous headache ≥2 weeks (<code>continuous_two_weeks_ind</code>)</p></li>
<li><p>Headache in the back of the head (<code>ha_back_head_ind</code>)</p></li>
<li><p>Weight loss (<code>weightloss_ind</code>)</p></li>
<li><p>Awakenings from sleep due to headache (<code>awakes_from_sleep_ind</code>)</p></li>
<li><p>Age ≤ 6 years (<code>sixoryounger_ind</code>)</p></li>
</ul></li>
</ul>
<p>The total red-flag score was then mapped to score-based recommendations intended to simulate a triage decision support tool:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Meaning</th>
<th>CDS Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>No concerning findings</td>
<td>Primary care management</td>
</tr>
<tr class="even">
<td>1–2</td>
<td>Moderate concern</td>
<td>Standard referral</td>
</tr>
<tr class="odd">
<td>≥3</td>
<td>High risk</td>
<td>Expedited referral</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct severe and minor red-flag components and total SmartForm score</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>ha <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Severe red flags: recurrent/persistent early morning vomiting and unsteady gait with headache</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">rf_severe_vomiting =</span> <span class="fu">if_else</span>(persistent_vomiting_ind <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1000</span>, <span class="dv">0</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">rf_severe_unsteady =</span> <span class="fu">if_else</span>(unsteady_gait_ind <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1000</span>, <span class="dv">0</span>),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Minor red flags: all other symptoms</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">rf_minor =</span> continuous_two_weeks_ind <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>      ha_back_head_ind <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>      weightloss_ind <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>      awakes_from_sleep_ind <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>      sixoryounger_ind,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Total red-flag score</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">redflag_score =</span> rf_severe_vomiting <span class="sc">+</span> rf_severe_unsteady <span class="sc">+</span> rf_minor,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Map score to recommendation</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">recommended_action =</span> <span class="fu">case_when</span>(</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>      redflag_score <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Primary care management recommended"</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>      redflag_score <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>) <span class="sc">~</span> <span class="st">"Standard neurology referral recommended"</span>,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>      redflag_score <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Expedited referral recommended"</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="categorizing-actual-provider-behavior" class="level3">
<h3 class="anchored" data-anchor-id="categorizing-actual-provider-behavior">1.4 Categorizing Actual Provider Behavior</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create categorical variable representing actual clinician referral decisions</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ha <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="at">actual_action =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>expedited_referral <span class="sc">~</span> <span class="st">"Expedited neurology referral placed"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>standard_referral <span class="sc">~</span> <span class="st">"Standard neurology referral placed"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span>any_neuro_referral <span class="sc">~</span> <span class="st">"No neurology referral placed"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other/unclear"</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="concordance-variable" class="level3">
<h3 class="anchored" data-anchor-id="concordance-variable">1.5 Concordance Variable</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define concordant = clinician action matches SmartForm recommendation</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ha <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="at">concordant =</span> <span class="fu">case_when</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>recommended_action <span class="sc">==</span> <span class="st">"Primary care management recommended"</span> <span class="sc">&amp;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>actual_action <span class="sc">==</span> <span class="st">"No neurology referral placed"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>recommended_action <span class="sc">==</span> <span class="st">"Standard neurology referral recommended"</span> <span class="sc">&amp;</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>actual_action <span class="sc">==</span> <span class="st">"Standard neurology referral placed"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>recommended_action <span class="sc">==</span> <span class="st">"Expedited referral recommended"</span> <span class="sc">&amp;</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>actual_action <span class="sc">==</span> <span class="st">"Expedited neurology referral placed"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="overall-referral-patterns" class="level3">
<h3 class="anchored" data-anchor-id="overall-referral-patterns">1.1 Overall Referral Patterns</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>overall_ref <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(actual_action) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>overall_ref</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  actual_action                           n   pct
  &lt;chr&gt;                               &lt;int&gt; &lt;dbl&gt;
1 Expedited neurology referral placed   161 0.111
2 No neurology referral placed         1116 0.769
3 Standard neurology referral placed    174 0.120</code></pre>
</div>
</div>
<p>A majority of encounters (76.9%) did not result in a neurology referral. Standard and expedited referrals were used in 12.0% and 11.1% of encounters, respectively. This baseline is essential for interpreting SmartForm effectiveness.</p>
</section>
<section id="recommended-vs.-actual-referral-behavior" class="level3">
<h3 class="anchored" data-anchor-id="recommended-vs.-actual-referral-behavior">1.2 Recommended vs.&nbsp;Actual Referral Behavior</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Cross-tab of Smartform recommendations vs. actual provider actions</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>rec_vs_actual <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(recommended_action, actual_action) <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">adorn_percentages</span>(<span class="st">"row"</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">adorn_pct_formatting</span>(<span class="at">digits =</span> <span class="dv">1</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>rec_vs_actual</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      recommended_action Expedited neurology referral placed
          Expedited referral recommended                               11.6%
     Primary care management recommended                               13.0%
 Standard neurology referral recommended                                8.4%
 No neurology referral placed Standard neurology referral placed
                        78.0%                              10.4%
                        69.5%                              17.5%
                        81.3%                              10.3%</code></pre>
</div>
</div>
<p>The SmartForm accurately identifies low-risk children, with 78% concordance when recommending primary care management. However, when recommending expedited referral, providers only agreed in 13% of encounters, suggesting significant misalignment between scoring and clinician judgment.</p>
</section>
<section id="concordance-summary" class="level3">
<h3 class="anchored" data-anchor-id="concordance-summary">1.3 Concordance Summary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ha <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">overall_concordance =</span> <span class="fu">mean</span>(concordant))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  overall_concordance
                &lt;dbl&gt;
1               0.245</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ha <span class="sc">|&gt;</span> <span class="fu">group_by</span>(recommended_action) <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="at">pct_concordant =</span> <span class="fu">mean</span>(concordant)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  recommended_action                          n pct_concordant
  &lt;chr&gt;                                   &lt;int&gt;          &lt;dbl&gt;
1 Expedited referral recommended            741          0.116
2 Primary care management recommended       331          0.695
3 Standard neurology referral recommended   379          0.103</code></pre>
</div>
</div>
</section>
<section id="visualizations" class="level3">
<h3 class="anchored" data-anchor-id="visualizations">1.4 Visualizations</h3>
<p>Figure 1: Stacked Bar Plot of Provider Actions vs.&nbsp;Recommendations</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ha, <span class="fu">aes</span>(<span class="at">x =</span> recommended_action, <span class="at">fill =</span> actual_action)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Primary care management recommended"</span> <span class="ot">=</span> <span class="st">"Primary Care"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Standard neurology referral recommended"</span> <span class="ot">=</span> <span class="st">"Standard Referral"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Expedited referral recommended"</span> <span class="ot">=</span> <span class="st">"Expedited Referral"</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Provider Actions vs SmartForm Recommendations"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"SmartForm Recommendation"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Actual Action"</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BMIN503_FinalProject_Kanakamedala_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 2: Overall Referral Proportions</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(overall_ref, <span class="fu">aes</span>(<span class="at">x =</span> actual_action, <span class="at">y =</span> pct)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Overall Neurology Referral Patterns"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="st">"Percent of Encounters"</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BMIN503_FinalProject_Kanakamedala_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 3: Concordance Plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>concord_plot <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(recommended_action) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="at">pct_concordant =</span> <span class="fu">mean</span>(concordant))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(concord_plot, <span class="fu">aes</span>(<span class="at">x =</span> recommended_action, <span class="at">y =</span> pct_concordant)) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Concordance Between SmartForm Recommendations and Provider Behavior"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Recommendation"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="st">"Percent Concordant"</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BMIN503_FinalProject_Kanakamedala_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="modeling" class="level2">
<h2 class="anchored" data-anchor-id="modeling">Modeling</h2>
<p>For the modeling analyses, I treated expedited_referral and any_neuro_referral as primary outcomes because these represent key operational decisions for neurology. Predictors included any_severe_flag (presence of persistent vomiting or unsteady gait) and minor_flag_count (count of other symptoms). This reflects the clinical design of the SmartForm, where severe findings are expected to drive urgent action, and minor findings may refine risk without independently mandating referral.</p>
<section id="severe-vs.-minor-red-flags-predicting-expedited-referral" class="level3">
<h3 class="anchored" data-anchor-id="severe-vs.-minor-red-flags-predicting-expedited-referral">1.1 Severe vs.&nbsp;Minor Red Flags: Predicting Expedited Referral</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ha <span class="ot">&lt;-</span> ha <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Any severe red flag present (persistent vomiting or unsteady gait)</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">any_severe_flag =</span> <span class="fu">if_else</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>      rf_severe_vomiting <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">|</span> rf_severe_unsteady <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>      <span class="dv">1</span>, <span class="dv">0</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Count of minor red flags</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">minor_flag_count =</span> rf_minor</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression: effect of severe and minor flags on EXPEDITED referrals</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>model_expedited <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  expedited_referral <span class="sc">~</span> any_severe_flag <span class="sc">+</span> minor_flag_count,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ha</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_expedited, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term             estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)         0.145     0.160    -12.1  1.31e-33    0.104     0.196
2 any_severe_flag     7.07      1.04       1.88 6.01e- 2    0.946    55.8  
3 minor_flag_count    0.662     0.227     -1.81 6.96e- 2    0.424     1.03 </code></pre>
</div>
</div>
<p>Patients with a severe red flag (persistent early-morning vomiting or unsteady gait) had higher odds of receiving an expedited neurology referral (OR ≈ 7), although this association was borderline significant. In contrast, each additional minor red flag was associated with lower odds of expedited referral (OR ≈ 0.66), indicating that clinicians do not treat an accumulation of minor symptoms as justification for urgent specialty evaluation. Overall, clinicians appear to reserve expedited referrals primarily for encounters involving clear severe neurological signs.</p>
</section>
<section id="predicting-any-referral" class="level3">
<h3 class="anchored" data-anchor-id="predicting-any-referral">1.2 Predicting Any Referral</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Logistic regression: predictors of ANY neurology referral</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>model_anyref <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>any_neuro_referral <span class="sc">~</span> any_severe_flag <span class="sc">+</span> minor_flag_count,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="at">family =</span> binomial,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="at">data =</span> ha</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_anyref, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term             estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)         0.419     0.117     -7.42 1.17e-13    0.332     0.525
2 any_severe_flag    10.0       0.760      3.03 2.46e- 3    2.29     45.1  
3 minor_flag_count    0.582     0.166     -3.26 1.12e- 3    0.419     0.804</code></pre>
</div>
</div>
<p>In this model, having at least one severe red flag (persistent early-morning vomiting or unsteady gait) was associated with about 10 times higher odds of receiving any neurology referral (OR ≈ 10.0, 95% CI 2.29–45.1, p = 0.002). In contrast, each additional minor red flag was associated with lower odds of any neurology referral (OR ≈ 0.58, 95% CI 0.42–0.80, p = 0.001), suggesting clinicians do not escalate referrals based on an accumulation of minor symptoms. Overall, neurology referral decisions in this dataset appear to be driven primarily by the presence of a severe neurologic sign rather than the total red-flag burden.</p>
</section>
<section id="predicting-concordance" class="level3">
<h3 class="anchored" data-anchor-id="predicting-concordance">1.3 Predicting Concordance</h3>
<p>I modeled concordant as a binary outcome to quantify how often clinical behavior matched the score’s recommendation and used recommended_action as the predictor to compare agreement rates across primary care, standard, and expedited recommendation categories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Logistic regression: how SmartForm recommendations predicts clinician concordance</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>model_concord <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>concordant <span class="sc">~</span> recommended_action,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="at">family =</span> binomial,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="at">data =</span> ha</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_concord, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term                  estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)              0.131     0.115   -17.7   4.04e-70    0.104     0.163
2 recommended_actionPr…   17.3       0.166    17.2   1.42e-66   12.6      24.1  
3 recommended_actionSt…    0.874     0.204    -0.661 5.08e- 1    0.580     1.29 </code></pre>
</div>
</div>
<p>Clinicians were 17 times more likely to be concordant when the SmartForm recommended <em>standard</em> neurology referral compared with the baseline category (primary care management), a highly significant association (p &lt; 0.0001). In contrast, expedited referral recommendations did not significantly increase concordance (OR ≈ 0.87, p = 0.51), meaning clinicians were no more likely to follow expedited recommendations than to diverge from them. Overall, this indicates that clinician behavior aligns well with standard referral recommendations but does not align with expedited referral recommendations, reinforcing miscalibration at the high-risk end of the score.</p>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>This project evaluated whether a SmartForm-derived red-flag scoring system for pediatric headache encounters aligns with clinician neurology referral behavior. By weighting two clinically severe findings (recurrent or persistent early-morning vomiting and unsteady gait) with 1000 points each, and all other red flags with 1 point each, the scoring system was intentionally designed to identify children at risk for neurologic pathology who may warrant expedited neurology evaluation. The results demonstrate that while the score discriminates low-risk encounters effectively, it does not accurately capture clinician judgment at the high-risk end of the spectrum.</p>
<p>The score showed strong performance for encounters in which no concerning symptoms were present. Primary care recommendations had the highest concordance with clinician behavior (≈76%), and logistic modeling confirmed that clinicians were unlikely to place any referral in the absence of severe red flags. This suggests that the SmartForm structure is well-aligned with provider decision-making for low-risk cases and may support safe reduction of unnecessary referrals.</p>
<p>In contrast, the scoring system over-classified encounters into the expedited referral category, leading to poor concordance (≈11%). Logistic regression reinforced this pattern: severe red flags increased the odds of expedited referral, but the effect size was reduced and borderline significant, indicating clinicians did not treat all severe-flag combinations as requiring urgent specialty evaluation. Minor red flags were associated with lower odds of referral across models, suggesting clinicians view these features as nonspecific and not additive. Importantly, clinicians were significantly more likely to agree with standard referral recommendations, whereas expedited recommendations did not influence behavior, further demonstrating that the high-risk threshold is miscalibrated.</p>
<p>Together, these findings indicate that clinician decision-making relies on clinical nuance not fully captured by the current weighted scoring system. The heavy weighting of severe symptoms guarantees that any child with a single severe red flag receives an expedited recommendation, even when the full clinical context may not support urgent referral. This design explains the high rate of discordance and highlights a critical area for redesign.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>The SmartForm-based red-flag scoring system successfully identifies encounters appropriate for primary care management but substantially overestimates the need for expedited neurology referrals. Clinicians reserve expedited referrals for only the most compelling neurologic concerns, whereas the scoring system classifies a larger proportion of children as high risk based solely on the presence of a single severe symptom. Logistic regression results support this interpretation: severe symptoms increase referral likelihood, but minor symptoms do not meaningfully contribute, and expedited referral recommendations do not align with actual provider behavior.</p>
<p>To improve its utility as clinical decision support, the scoring system requires recalibration, specifically, moderating the extreme weighting of severe red flags, differentiating levels of risk within the high-severity group, and potentially integrating additional contextual factors. A more flexible or probabilistic scoring model may better reflect real-world clinician decision patterns and improve alignment with neurology referral workflows. Future iterations will need to be validated prospectively and evaluated for impact on referral volume, appropriateness, and patient outcomes.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>
<script>window.backupDefine = window.define; window.define = undefined;</script>
<script type="text/javascript" src="quarto-preview.js"></script>
<script>window.define = window.backupDefine; window.backupDefine = undefined;</script>
<script type="text/javascript">
  const options = {
    origin: "",
    search: "",
    inputFile: "/Users/kanakamedl/Desktop/BMIN503_FinalProject_Kanakamedala.qmd",
    isPresentation: false
  }
  document.addEventListener("DOMContentLoaded", function () {
    window.QuartoPreview.init(options);
  });
</script>

<script>window.backupDefine = window.define; window.define = undefined;</script>
<script type="text/javascript" src="quarto-preview.js"></script>
<script>window.define = window.backupDefine; window.backupDefine = undefined;</script>
<script type="text/javascript">
  const options = {
    origin: "",
    search: "",
    inputFile: "/Users/kanakamedl/Desktop/BMIN503_FinalProject_Kanakamedala.qmd",
    isPresentation: false
  }
  document.addEventListener("DOMContentLoaded", function () {
    window.QuartoPreview.init(options);
  });
</script>
